"""
Figure generation script for streaming QEC protocol paper.
Loads data generated by comprehensive_data_generation.py and creates publication-quality figures.

Creates all figures needed for the paper:
1. Error evolution plots
2. Fidelity evolution plots  
3. Memory scaling demonstration (KEY FIGURE)
4. Phase diagrams
5. QEC protocol comparison charts
6. Convergence analysis plots
7. Threshold analysis plots
8. Noise model comparison plots
9. Resource overhead analysis
10. Amplification efficiency plots
"""

import os
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from typing import Dict, List, Tuple, Any, Optional
from dataclasses import dataclass
import warnings
from matplotlib.patches import Patch
from matplotlib.colors import LinearSegmentedColormap
import matplotlib.patches as patches

# Set publication-quality plotting parameters (fix font issues)
plt.style.use('seaborn-v0_8-paper')
sns.set_palette("husl")

plt.rcParams.update({
    'font.size': 12,
    'axes.titlesize': 14,
    'axes.labelsize': 12,
    'xtick.labelsize': 10,
    'ytick.labelsize': 10,
    'legend.fontsize': 10,
    'figure.titlesize': 16,
    'font.family': 'DejaVu Sans',  # Changed from Times New Roman to avoid subscript issues
    'mathtext.fontset': 'dejavusans',  # Changed to match font
    'axes.linewidth': 1.2,
    'grid.linewidth': 0.8,
    'lines.linewidth': 2,
    'lines.markersize': 6
})

# Color schemes for different protocols/noise types
PROTOCOL_COLORS = {
    'depolarizing': '#2E86AB',
    'symmetric_pauli': '#A23B72', 
    'dephasing': '#F18F01',
    'streaming_qec': '#2E86AB',
    'surface_code': '#A23B72',
    'spinor_code': '#F18F01',
    'css_codes': '#C73E1D'
}


class StreamingQECFigureGenerator:
    """Generate all publication-quality figures for streaming QEC paper."""
    
    def __init__(self, data_dir: str = "data", figures_dir: str = "figures"):
        self.data_dir = data_dir
        self.figures_dir = figures_dir
        os.makedirs(figures_dir, exist_ok=True)
        
        # Load all data
        self.data = self._load_all_data()
    
    def _load_all_data(self) -> Dict[str, Any]:
        """Load all generated data from files."""
        print("Loading comprehensive data...")
        
        data = {}
        
        # Find the most recent data files
        metadata_files = [f for f in os.listdir(os.path.join(self.data_dir, "metadata")) 
                         if f.startswith("comprehensive_metadata_")]
        
        if not metadata_files:
            raise FileNotFoundError("No comprehensive metadata found. Run comprehensive_data_generation.py first.")
        
        # Load most recent metadata
        latest_metadata = sorted(metadata_files)[-1]
        with open(os.path.join(self.data_dir, "metadata", latest_metadata), 'r') as f:
            metadata = json.load(f)
        
        timestamp = metadata['timestamp']
        print(f"Loading data from timestamp: {timestamp}")
        
        # Load each data type
        data_types = ['evolution', 'threshold', 'resource', 'phase_diagrams', 
                     'qec_comparisons', 'convergence', 'noise_analysis', 
                     'memory_scaling', 'amplification']
        
        for data_type in data_types:
            json_file = os.path.join(self.data_dir, data_type, f"{data_type}_{timestamp}.json")
            if os.path.exists(json_file):
                with open(json_file, 'r') as f:
                    data[data_type] = json.load(f)
                print(f"  Loaded {data_type}")
            else:
                print(f"  Warning: {data_type} data not found")
        
        return data
    
    def generate_all_figures(self, save_format: str = 'pdf') -> Dict[str, str]:
        """Generate all figures and save as PDFs."""
        print("\n" + "="*60)
        print("GENERATING ALL PUBLICATION FIGURES")
        print("="*60)
        
        saved_figures = {}
        
        # 1. Memory Scaling (KEY FIGURE)
        print("\n1. Memory scaling demonstration...")
        if 'memory_scaling' in self.data:
            fig_path = self.plot_memory_scaling(save_format)
            saved_figures['memory_scaling'] = fig_path
        
        # 2. Evolution Plots
        print("\n2. Error and fidelity evolution plots...")
        if 'evolution' in self.data:
            error_path = self.plot_error_evolution(save_format)
            fidelity_path = self.plot_fidelity_evolution(save_format)
            saved_figures['error_evolution'] = error_path
            saved_figures['fidelity_evolution'] = fidelity_path
        
        # 3. Phase Diagrams
        print("\n3. Phase diagrams...")
        if 'phase_diagrams' in self.data:
            phase_paths = self.plot_phase_diagrams(save_format)
            saved_figures.update(phase_paths)
        
        # 4. QEC Comparison
        print("\n4. QEC protocol comparison...")
        if 'qec_comparisons' in self.data:
            comparison_path = self.plot_qec_comparison(save_format)
            saved_figures['qec_comparison'] = comparison_path
        
        # 5. Convergence Analysis
        print("\n5. Convergence analysis...")
        if 'convergence' in self.data:
            convergence_path = self.plot_convergence_analysis(save_format)
            saved_figures['convergence_analysis'] = convergence_path
        
        # 6. Threshold Analysis
        print("\n6. Threshold analysis...")
        if 'threshold' in self.data:
            threshold_path = self.plot_threshold_analysis(save_format)
            saved_figures['threshold_analysis'] = threshold_path
        
        # 7. Noise Model Comparison
        print("\n7. Noise model comparison...")
        if 'noise_analysis' in self.data:
            noise_path = self.plot_noise_model_comparison(save_format)
            saved_figures['noise_comparison'] = noise_path
        
        # 8. Resource Overhead
        print("\n8. Resource overhead analysis...")
        if 'resource' in self.data:
            resource_path = self.plot_resource_overhead(save_format)
            saved_figures['resource_overhead'] = resource_path
        
        # 9. Amplification Efficiency
        print("\n9. Amplification efficiency...")
        if 'amplification' in self.data:
            amp_path = self.plot_amplification_efficiency(save_format)
            saved_figures['amplification_efficiency'] = amp_path
        
        # 10. Combined Main Figure (Figure 1 style)
        print("\n10. Combined main figure...")
        main_fig_path = self.create_main_figure(save_format)
        saved_figures['main_figure'] = main_fig_path
        
        print(f"\n{len(saved_figures)} figures saved to: {self.figures_dir}")
        return saved_figures
    
    def plot_memory_scaling(self, save_format: str = 'pdf') -> str:
        """Plot memory scaling - THE KEY ADVANTAGE FIGURE."""
        fig, ax = plt.subplots(figsize=(10, 6))
        
        if 'memory_scaling' not in self.data or not self.data['memory_scaling']:
            print("Warning: No memory scaling data found")
            ax.text(0.5, 0.5, 'No Memory Scaling Data Available', 
                   transform=ax.transAxes, ha='center', va='center', fontsize=16)
            ax.set_title('Memory Scaling (No Data)')
        else:
            data = self.data['memory_scaling']
            N_values = data['N_values']
            streaming = data['streaming_memory']
            standard = data['standard_qec_memory']
            theoretical = data['theoretical_log_N']
            
            print(f"Plotting memory scaling with {len(N_values)} data points")
            
            # Main scaling plots
            ax.loglog(N_values, streaming, 'o-', color=PROTOCOL_COLORS['streaming_qec'],
                     label='Streaming QEC (O(log N))', linewidth=3, markersize=8)
            ax.loglog(N_values, standard, 's-', color=PROTOCOL_COLORS['surface_code'],
                     label='Standard QEC (O(N))', linewidth=3, markersize=8)
            ax.loglog(N_values, theoretical, '--', color='gray', alpha=0.7,
                     label='Theoretical log_2(N)', linewidth=2)  # Changed subscript to underscore
            
            # Add advantage annotation
            if 'memory_advantage' in data and data['memory_advantage']:
                max_advantage = max(data['memory_advantage'])
                ax.text(0.65, 0.25, f'Max Advantage:\n{max_advantage:.0f}x reduction', 
                        transform=ax.transAxes, fontsize=12, 
                        bbox=dict(boxstyle="round,pad=0.5", facecolor="yellow", alpha=0.8),
                        ha='center')
            
            # Add scaling annotations
            ax.text(0.75, 0.85, 'O(N)', transform=ax.transAxes, fontsize=14, 
                    color=PROTOCOL_COLORS['surface_code'], fontweight='bold')
            ax.text(0.75, 0.15, 'O(log N)', transform=ax.transAxes, fontsize=14,
                    color=PROTOCOL_COLORS['streaming_qec'], fontweight='bold')
        
        # Formatting
        ax.set_xlabel('Number of Input States (N)', fontsize=14)
        ax.set_ylabel('Memory Requirements (qubits)', fontsize=14)
        ax.set_title('Memory Scaling: Streaming vs Standard QEC', fontsize=16, fontweight='bold')
        ax.legend(fontsize=12, loc='upper left')
        ax.grid(True, alpha=0.3)
        
        plt.tight_layout()
        
        filename = f"memory_scaling_advantage.{save_format}"
        filepath = os.path.join(self.figures_dir, filename)
        plt.savefig(filepath, dpi=300, bbox_inches='tight', format=save_format)
        plt.close()
        
        return filepath
    
    def plot_error_evolution(self, save_format: str = 'pdf') -> str:
        """Plot logical error evolution through purification levels."""
        fig, ax = plt.subplots(figsize=(10, 6))
        
        evolution_data = self.data['evolution']
        
        # Debug: Check if we have data
        if not evolution_data:
            print("Warning: No evolution data found")
            # Create placeholder plot
            ax.text(0.5, 0.5, 'No Evolution Data Available', 
                   transform=ax.transAxes, ha='center', va='center', fontsize=16)
            ax.set_title('Error Evolution (No Data)')
        else:
            print(f"Found {len(evolution_data)} evolution records")
            
            # Group by noise type and plot representative examples
            noise_types = ['depolarizing', 'symmetric_pauli']
            linestyles = ['-', '--']
            colors = [PROTOCOL_COLORS['depolarizing'], PROTOCOL_COLORS['symmetric_pauli']]
            
            plots_created = 0
            
            for i, noise_type in enumerate(noise_types):
                # Find a representative example (moderate error rate, reasonable N)
                examples = [d for d in evolution_data 
                           if d['noise_type'] == noise_type 
                           and abs(d['physical_error_rate'] - 0.3) < 0.1
                           and d['N'] >= 16]
                
                if not examples:
                    # Try with any available data for this noise type
                    examples = [d for d in evolution_data if d['noise_type'] == noise_type]
                
                if examples:
                    data = examples[0]  # Use first available example
                    iterations = data['iterations']
                    errors = data['logical_errors']
                    
                    if len(iterations) > 0 and len(errors) > 0:
                        color = colors[i]
                        
                        # Plot simulation
                        ax.semilogy(iterations, errors, 'o-', color=color, linestyle=linestyles[i],
                                   label=f'{noise_type.replace("_", " ").title()} (N={data["N"]}, p={data["physical_error_rate"]:.2f})', 
                                   linewidth=2, markersize=6)
                        plots_created += 1
                        
                        # Plot theoretical if available
                        if 'theoretical_predictions' in data and data['theoretical_predictions']:
                            theoretical = data['theoretical_predictions']
                            if len(theoretical) == len(iterations):
                                ax.semilogy(iterations, theoretical, '--', color=color, alpha=0.7,
                                           label=f'{noise_type.replace("_", " ").title()} (Theory)', 
                                           linewidth=2)
            
            if plots_created == 0:
                ax.text(0.5, 0.5, 'No Valid Evolution Data Found', 
                       transform=ax.transAxes, ha='center', va='center', fontsize=16)
        
        ax.set_xlabel('Purification Level', fontsize=14)
        ax.set_ylabel('Logical Error Rate', fontsize=14)
        ax.set_title('Logical Error Evolution', fontsize=16, fontweight='bold')
        
        # Only add legend if we have plots
        handles, labels = ax.get_legend_handles_labels()
        if handles:
            ax.legend(fontsize=11)
        
        ax.grid(True, alpha=0.3)
        
        # Add improvement annotations if we have data
        if 'evolution' in self.data and self.data['evolution']:
            ax.text(0.7, 0.8, 'Error\nReduction', transform=ax.transAxes, fontsize=12,
                    bbox=dict(boxstyle="round,pad=0.3", facecolor="lightgreen", alpha=0.7))
        
        plt.tight_layout()
        
        filename = f"error_evolution.{save_format}"
        filepath = os.path.join(self.figures_dir, filename)
        plt.savefig(filepath, dpi=300, bbox_inches='tight', format=save_format)
        plt.close()
        
        return filepath
    
    def plot_fidelity_evolution(self, save_format: str = 'pdf') -> str:
        """Plot fidelity evolution through purification levels."""
        fig, ax = plt.subplots(figsize=(10, 6))
        
        evolution_data = self.data['evolution']
        
        # Plot for different initial error rates
        error_rates = [0.1, 0.3, 0.5]
        colors = ['green', 'orange', 'red']
        
        for i, error_rate in enumerate(error_rates):
            # Find depolarizing examples
            examples = [d for d in evolution_data 
                       if d['noise_type'] == 'depolarizing'
                       and abs(d['physical_error_rate'] - error_rate) < 0.05
                       and d['N'] == 32]
            
            if examples:
                data = examples[0]
                iterations = data['iterations']
                fidelities = data['fidelities']
                
                ax.plot(iterations, fidelities, 'o-', color=colors[i],
                       label=f'p = {error_rate}', linewidth=2, markersize=6)
        
        ax.set_xlabel('Purification Level', fontsize=14)
        ax.set_ylabel('State Fidelity', fontsize=14)
        ax.set_title('Fidelity Evolution (Depolarizing Noise, N = 32)', fontsize=16, fontweight='bold')
        ax.legend(fontsize=12)
        ax.grid(True, alpha=0.3)
        ax.set_ylim(0, 1.05)
        
        # Add target line
        ax.axhline(y=0.99, color='black', linestyle=':', alpha=0.7, label='High Fidelity Target')
        ax.legend(fontsize=12)
        
        plt.tight_layout()
        
        filename = f"fidelity_evolution.{save_format}"
        filepath = os.path.join(self.figures_dir, filename)
        plt.savefig(filepath, dpi=300, bbox_inches='tight', format=save_format)
        plt.close()
        
        return filepath
    
    def plot_phase_diagrams(self, save_format: str = 'pdf') -> Dict[str, str]:
        """Plot phase diagrams for different noise types."""
        saved_paths = {}
        
        if 'phase_diagrams' not in self.data or not self.data['phase_diagrams']:
            print("Warning: No phase diagram data found")
            return saved_paths
        
        phase_data = self.data['phase_diagrams']
        
        for i, data in enumerate(phase_data):
            try:
                noise_type = data['noise_type']
                dimension = data['dimension']
                
                fig, ax = plt.subplots(figsize=(10, 8))
                
                # Convert to numpy arrays safely
                error_rates = np.array(data['error_rates'])
                code_sizes = np.array(data['code_sizes'])
                success_matrix = np.array(data['success_matrix'])
                threshold_curve = np.array(data['threshold_curve'])
                
                # Ensure arrays have correct shapes
                if success_matrix.shape != (len(error_rates), len(code_sizes)):
                    print(f"Warning: Shape mismatch in success_matrix for {noise_type}")
                    continue
                
                # Create meshgrid
                X, Y = np.meshgrid(code_sizes, error_rates)
                
                # Plot phase diagram
                colors = ['lightcoral', 'lightgreen']
                levels = [0, 0.5, 1]
                contour_fill = ax.contourf(X, Y, success_matrix, levels=levels, 
                                         colors=colors, alpha=0.8)
                
                # Plot threshold line safely
                if len(threshold_curve) == len(code_sizes):
                    ax.plot(code_sizes, threshold_curve, 'k-', linewidth=3, 
                           label='Error Threshold')
                
                # Formatting
                ax.set_xscale('log', base=2)
                ax.set_xlabel('Code Size (N)', fontsize=14)
                ax.set_ylabel('Physical Error Rate', fontsize=14)
                ax.set_title(f'Phase Diagram: {noise_type.replace("_", " ").title()} Noise (d={dimension})', 
                            fontsize=16, fontweight='bold')
                
                # Legend
                legend_elements = [
                    Patch(facecolor='lightcoral', label='Failure Region'),
                    Patch(facecolor='lightgreen', label='Success Region'),
                    plt.Line2D([0], [0], color='black', linewidth=3, label='Threshold')
                ]
                ax.legend(handles=legend_elements, fontsize=12, loc='upper right')
                
                ax.grid(True, alpha=0.3)
                
                plt.tight_layout()
                
                filename = f"phase_diagram_{noise_type}_d{dimension}.{save_format}"
                filepath = os.path.join(self.figures_dir, filename)
                plt.savefig(filepath, dpi=300, bbox_inches='tight', format=save_format)
                plt.close()
                
                # Use string key instead of potentially problematic data reference
                key = f'phase_{noise_type}_d{dimension}'
                saved_paths[key] = filepath
                print(f"Saved phase diagram: {filename}")
                
            except Exception as e:
                print(f"Error generating phase diagram for {data.get('noise_type', 'unknown')}: {e}")
                continue
        
        return saved_paths
    
    def plot_qec_comparison(self, save_format: str = 'pdf') -> str:
        """Plot comparison with existing QEC protocols."""
        fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(14, 10))
        
        comparison_data = self.data['qec_comparisons']
        
        protocols = [d['protocol_name'] for d in comparison_data]
        thresholds = [d['threshold'] for d in comparison_data]
        memory_complexities = [d['memory_complexity'] for d in comparison_data]
        gate_complexities = [d['gate_complexity_estimate'] for d in comparison_data]
        
        colors = [PROTOCOL_COLORS.get(p.lower().split()[0], '#666666') for p in protocols]
        
        # 1. Threshold comparison
        bars1 = ax1.bar(range(len(protocols)), thresholds, color=colors, alpha=0.8)
        ax1.set_ylabel('Error Threshold', fontsize=12)
        ax1.set_title('Error Thresholds', fontsize=14, fontweight='bold')
        ax1.set_xticks(range(len(protocols)))
        ax1.set_xticklabels([p.split()[0] for p in protocols], rotation=45, ha='right')
        ax1.grid(True, alpha=0.3)
        
        # Add threshold values on bars
        for bar, threshold in zip(bars1, thresholds):
            height = bar.get_height()
            ax1.text(bar.get_x() + bar.get_width()/2., height + 0.01,
                    f'{threshold:.0%}', ha='center', va='bottom', fontsize=10)
        
        # 2. Memory complexity (categorical)
        memory_order = {'O(log N)': 1, 'O(N)': 2, 'O(N²)': 3}
        memory_values = [memory_order.get(m, 2) for m in memory_complexities]
        
        bars2 = ax2.bar(range(len(protocols)), memory_values, color=colors, alpha=0.8)
        ax2.set_ylabel('Memory Complexity', fontsize=12)
        ax2.set_title('Memory Requirements', fontsize=14, fontweight='bold')
        ax2.set_xticks(range(len(protocols)))
        ax2.set_xticklabels([p.split()[0] for p in protocols], rotation=45, ha='right')
        ax2.set_yticks([1, 2, 3])
        ax2.set_yticklabels(['O(log N)', 'O(N)', 'O(N²)'])
        ax2.grid(True, alpha=0.3)
        
        # 3. Gate complexity
        bars3 = ax3.bar(range(len(protocols)), gate_complexities, color=colors, alpha=0.8)
        ax3.set_ylabel('Gate Complexity (Estimate)', fontsize=12)
        ax3.set_title('Implementation Overhead', fontsize=14, fontweight='bold')
        ax3.set_xticks(range(len(protocols)))
        ax3.set_xticklabels([p.split()[0] for p in protocols], rotation=45, ha='right')
        ax3.grid(True, alpha=0.3)
        
        # 4. Combined advantage plot (threshold vs memory efficiency)
        memory_efficiency = [1/memory_values[i] for i in range(len(protocols))]
        
        for i, protocol in enumerate(protocols):
            ax4.scatter(thresholds[i], memory_efficiency[i], 
                       color=colors[i], s=150, alpha=0.8, label=protocol.split()[0])
        
        ax4.set_xlabel('Error Threshold', fontsize=12)
        ax4.set_ylabel('Memory Efficiency (1/complexity)', fontsize=12)
        ax4.set_title('Protocol Trade-offs', fontsize=14, fontweight='bold')
        ax4.legend(fontsize=10)
        ax4.grid(True, alpha=0.3)
        
        # Highlight streaming QEC advantage
        streaming_idx = 0  # First protocol is streaming
        ax4.annotate('Our Work:\nHigh threshold +\nLow memory', 
                    xy=(thresholds[streaming_idx], memory_efficiency[streaming_idx]),
                    xytext=(0.3, 0.8), textcoords='axes fraction',
                    arrowprops=dict(arrowstyle='->', color='red', lw=2),
                    fontsize=11, ha='center',
                    bbox=dict(boxstyle="round,pad=0.3", facecolor="yellow", alpha=0.8))
        
        plt.tight_layout()
        
        filename = f"qec_protocol_comparison.{save_format}"
        filepath = os.path.join(self.figures_dir, filename)
        plt.savefig(filepath, dpi=300, bbox_inches='tight', format=save_format)
        plt.close()
        
        return filepath
    
    def plot_convergence_analysis(self, save_format: str = 'pdf') -> str:
        """Plot detailed convergence analysis."""
        fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(14, 10))
        
        convergence_data = self.data['convergence']
        
        # Colors for different initial deltas
        colors = plt.cm.viridis(np.linspace(0, 1, len(convergence_data)))
        
        # 1. Purity evolution
        for i, data in enumerate(convergence_data):
            levels = data['purification_levels']
            purity = data['purity_evolution']
            delta = data['initial_delta']
            
            ax1.plot(levels, purity, 'o-', color=colors[i], 
                    label=f'δ = {delta}', linewidth=2, markersize=4)
        
        ax1.set_xlabel('Purification Level', fontsize=12)
        ax1.set_ylabel('Purity Parameter λ', fontsize=12)
        ax1.set_title('Purity Evolution', fontsize=14, fontweight='bold')
        ax1.legend(fontsize=9, ncol=2)
        ax1.grid(True, alpha=0.3)
        ax1.set_ylim(0, 1.05)
        
        # 2. Logical error evolution (log scale)
        for i, data in enumerate(convergence_data):
            levels = data['purification_levels']
            errors = data['logical_error_evolution']
            delta = data['initial_delta']
            
            ax2.semilogy(levels, errors, 'o-', color=colors[i], 
                        label=f'δ = {delta}', linewidth=2, markersize=4)
        
        ax2.set_xlabel('Purification Level', fontsize=12)
        ax2.set_ylabel('Logical Error Rate', fontsize=12)
        ax2.set_title('Error Reduction', fontsize=14, fontweight='bold')
        ax2.grid(True, alpha=0.3)
        
        # 3. Success probabilities
        for i, data in enumerate(convergence_data):
            if len(data['success_probabilities']) > 0:
                levels = list(range(1, len(data['success_probabilities']) + 1))
                success_probs = data['success_probabilities']
                delta = data['initial_delta']
                
                ax3.plot(levels, success_probs, 'o-', color=colors[i], 
                        label=f'δ = {delta}', linewidth=2, markersize=4)
        
        ax3.set_xlabel('Purification Level', fontsize=12)
        ax3.set_ylabel('Swap Test Success Probability', fontsize=12)
        ax3.set_title('Success Probability Evolution', fontsize=14, fontweight='bold')
        ax3.grid(True, alpha=0.3)
        ax3.set_ylim(0, 1.05)
        
        # 4. Convergence rate vs initial error
        initial_deltas = [data['initial_delta'] for data in convergence_data]
        convergence_rates = [data['convergence_rate'] for data in convergence_data]
        final_purities = [data['purity_evolution'][-1] for data in convergence_data]
        
        # Create scatter plot with color representing final purity
        scatter = ax4.scatter(initial_deltas, convergence_rates, c=final_purities, 
                            cmap='RdYlGn', s=100, alpha=0.8)
        
        ax4.set_xlabel('Initial Error Rate δ', fontsize=12)
        ax4.set_ylabel('Average Convergence Rate', fontsize=12)
        ax4.set_title('Convergence Rate vs Initial Error', fontsize=14, fontweight='bold')
        ax4.grid(True, alpha=0.3)
        
        # Add colorbar
        cbar = plt.colorbar(scatter, ax=ax4)
        cbar.set_label('Final Purity', fontsize=10)
        
        plt.tight_layout()
        
        filename = f"convergence_analysis.{save_format}"
        filepath = os.path.join(self.figures_dir, filename)
        plt.savefig(filepath, dpi=300, bbox_inches='tight', format=save_format)
        plt.close()
        
        return filepath
    
    def plot_threshold_analysis(self, save_format: str = 'pdf') -> str:
        """Plot threshold analysis across different parameters."""
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))
        
        threshold_data = self.data['threshold']
        
        # Group by noise type and dimension
        noise_types = list(set(d['noise_type'] for d in threshold_data))
        dimensions = list(set(d['dimension'] for d in threshold_data))
        
        # 1. Threshold curves for different noise types (d=2)
        for noise_type in noise_types:
            # Find data for d=2, largest N
            examples = [d for d in threshold_data 
                       if d['noise_type'] == noise_type 
                       and d['dimension'] == 2]
            
            if examples:
                # Use largest N available
                data = max(examples, key=lambda x: x['N'])
                
                error_rates = data['physical_error_rates']
                final_errors = data['final_logical_errors']
                
                # Filter out infinite values
                valid_indices = [i for i, err in enumerate(final_errors) if np.isfinite(err)]
                if valid_indices:
                    valid_rates = [error_rates[i] for i in valid_indices]
                    valid_errors = [final_errors[i] for i in valid_indices]
                    
                    color = PROTOCOL_COLORS[noise_type]
                    ax1.semilogy(valid_rates, valid_errors, 'o-', color=color,
                               label=f'{noise_type.replace("_", " ").title()} (N={data["N"]})',
                               linewidth=2, markersize=5)
        
        # Add "no improvement" reference line
        ref_rates = np.linspace(0.05, 0.8, 50)
        ax1.semilogy(ref_rates, ref_rates, '--', color='gray', alpha=0.7,
                    label='No Improvement')
        
        ax1.set_xlabel('Physical Error Rate', fontsize=12)
        ax1.set_ylabel('Final Logical Error Rate', fontsize=12)
        ax1.set_title('Threshold Behavior (d=2)', fontsize=14, fontweight='bold')
        ax1.legend(fontsize=11)
        ax1.grid(True, alpha=0.3)
        
        # 2. Error reduction ratio vs code size
        for noise_type in noise_types:
            if noise_type == 'depolarizing':  # Focus on best-performing case
                examples = [d for d in threshold_data 
                           if d['noise_type'] == noise_type 
                           and d['dimension'] == 2]
                
                code_sizes = []
                avg_reductions = []
                
                for data in examples:
                    N = data['N']
                    reductions = data['error_reduction_ratios']
                    
                    # Average reduction for moderate error rates (0.2-0.5)
                    error_rates = data['physical_error_rates']
                    moderate_indices = [i for i, rate in enumerate(error_rates) 
                                      if 0.2 <= rate <= 0.5 and np.isfinite(reductions[i])]
                    
                    if moderate_indices:
                        avg_reduction = np.mean([reductions[i] for i in moderate_indices])
                        code_sizes.append(N)
                        avg_reductions.append(avg_reduction)
                
                if code_sizes:
                    ax2.semilogx(code_sizes, avg_reductions, 'o-', 
                               color=PROTOCOL_COLORS[noise_type],
                               label=f'{noise_type.replace("_", " ").title()}',
                               linewidth=2, markersize=6)
        
        ax2.set_xlabel('Code Size (N)', fontsize=12)
        ax2.set_ylabel('Average Error Reduction Ratio', fontsize=12)
        ax2.set_title('Error Reduction vs Code Size', fontsize=14, fontweight='bold')
        ax2.legend(fontsize=11)
        ax2.grid(True, alpha=0.3)
        ax2.axhline(y=1.0, color='gray', linestyle='--', alpha=0.7, label='No Improvement')
        
        plt.tight_layout()
        
        filename = f"threshold_analysis.{save_format}"
        filepath = os.path.join(self.figures_dir, filename)
        plt.savefig(filepath, dpi=300, bbox_inches='tight', format=save_format)
        plt.close()
        
        return filepath
    
    def plot_noise_model_comparison(self, save_format: str = 'pdf') -> str:
        """Plot detailed noise model comparison."""
        fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(14, 10))
        
        noise_analysis = self.data['noise_analysis']
        
        error_rates = [data['physical_error_rate'] for data in noise_analysis]
        
        # Extract data for depolarizing vs Pauli comparison
        depolarizing_final = []
        pauli_final = []
        depolarizing_reduction = []
        pauli_reduction = []
        bloch_preservation = []
        coherence_metrics = []
        
        for data in noise_analysis:
            noise_types = data['noise_types']
            final_errors = data['final_logical_errors']
            reductions = data['error_reduction_ratios']
            bloch = data['bloch_vector_preservation']
            coherence = data['coherence_metrics']
            
            # Assuming first is depolarizing, second is Pauli
            if len(final_errors) >= 2:
                depolarizing_final.append(final_errors[0])
                pauli_final.append(final_errors[1])
                depolarizing_reduction.append(reductions[0])
                pauli_reduction.append(reductions[1])
                bloch_preservation.extend(bloch)
                coherence_metrics.extend(coherence)
        
        # 1. Final error comparison
        ax1.semilogy(error_rates, depolarizing_final, 'o-', 
                    color=PROTOCOL_COLORS['depolarizing'],
                    label='Depolarizing', linewidth=2, markersize=6)
        ax1.semilogy(error_rates, pauli_final, 's-', 
                    color=PROTOCOL_COLORS['symmetric_pauli'],
                    label='Symmetric Pauli', linewidth=2, markersize=6)
        ax1.semilogy(error_rates, error_rates, '--', color='gray', alpha=0.7,
                    label='No Improvement')
        
        ax1.set_xlabel('Physical Error Rate', fontsize=12)
        ax1.set_ylabel('Final Logical Error Rate', fontsize=12)
        ax1.set_title('Final Error: Depolarizing vs Pauli', fontsize=14, fontweight='bold')
        ax1.legend(fontsize=11)
        ax1.grid(True, alpha=0.3)
        
        # 2. Error reduction ratio comparison
        ax2.plot(error_rates, depolarizing_reduction, 'o-', 
                color=PROTOCOL_COLORS['depolarizing'],
                label='Depolarizing', linewidth=2, markersize=6)
        ax2.plot(error_rates, pauli_reduction, 's-', 
                color=PROTOCOL_COLORS['symmetric_pauli'],
                label='Symmetric Pauli', linewidth=2, markersize=6)
        ax2.axhline(y=1.0, color='gray', linestyle='--', alpha=0.7)
        
        ax2.set_xlabel('Physical Error Rate', fontsize=12)
        ax2.set_ylabel('Error Reduction Ratio', fontsize=12)
        ax2.set_title('Error Reduction Effectiveness', fontsize=14, fontweight='bold')
        ax2.legend(fontsize=11)
        ax2.grid(True, alpha=0.3)
        
        # 3. Bloch vector preservation
        if len(bloch_preservation) >= len(error_rates) * 2:
            dep_bloch = bloch_preservation[::2]  # Every other element
            pauli_bloch = bloch_preservation[1::2]
            
            ax3.plot(error_rates, dep_bloch, 'o-', 
                    color=PROTOCOL_COLORS['depolarizing'],
                    label='Depolarizing', linewidth=2, markersize=6)
            ax3.plot(error_rates, pauli_bloch, 's-', 
                    color=PROTOCOL_COLORS['symmetric_pauli'],
                    label='Symmetric Pauli', linewidth=2, markersize=6)
        
        ax3.set_xlabel('Physical Error Rate', fontsize=12)
        ax3.set_ylabel('Bloch Vector Preservation', fontsize=12)
        ax3.set_title('Coherence Preservation', fontsize=14, fontweight='bold')
        ax3.legend(fontsize=11)
        ax3.grid(True, alpha=0.3)
        ax3.set_ylim(0, 1.05)
        
        # 4. Advantage ratio (depolarizing / Pauli)
        advantage_ratios = [dep/pauli if pauli > 0 else 1 
                           for dep, pauli in zip(depolarizing_reduction, pauli_reduction)]
        
        ax4.plot(error_rates, advantage_ratios, 'o-', 
                color='purple', linewidth=2, markersize=6)
        ax4.axhline(y=1.0, color='gray', linestyle='--', alpha=0.7)
        
        ax4.set_xlabel('Physical Error Rate', fontsize=12)
        ax4.set_ylabel('Advantage Ratio (Depol./Pauli)', fontsize=12)
        ax4.set_title('Depolarizing Advantage', fontsize=14, fontweight='bold')
        ax4.grid(True, alpha=0.3)
        
        # Add explanation text
        explanation = ("Depolarizing noise preserves target state direction,\n"
                      "enabling precise purity amplification.\n"
                      "Pauli errors introduce cross-coherence terms.")
        ax4.text(0.05, 0.95, explanation, transform=ax4.transAxes, fontsize=10,
                verticalalignment='top',
                bbox=dict(boxstyle="round,pad=0.3", facecolor="lightblue", alpha=0.7))
        
        plt.tight_layout()
        
        filename = f"noise_model_comparison.{save_format}"
        filepath = os.path.join(self.figures_dir, filename)
        plt.savefig(filepath, dpi=300, bbox_inches='tight', format=save_format)
        plt.close()
        
        return filepath
    
    def plot_resource_overhead(self, save_format: str = 'pdf') -> str:
        """Plot resource overhead analysis."""
        fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(14, 10))
        
        resource_data = self.data['resource']
        
        # Group by noise type and extract data
        depolarizing_data = [d for d in resource_data if d['noise_type'] == 'depolarizing']
        
        if depolarizing_data:
            N_values = [d['N'] for d in depolarizing_data]
            memory_used = [d['memory_levels_used'] for d in depolarizing_data]
            theoretical_memory = [d['theoretical_memory'] for d in depolarizing_data]
            swap_ops = [d['total_swap_operations'] for d in depolarizing_data]
            amp_iterations = [d['total_amplification_iterations'] for d in depolarizing_data]
            gate_complexity = [d['gate_complexity'] for d in depolarizing_data]
            
            # 1. Memory usage vs theoretical
            ax1.semilogx(N_values, memory_used, 'o-', color=PROTOCOL_COLORS['streaming_qec'],
                        label='Actual Memory Used', linewidth=2, markersize=6)
            ax1.semilogx(N_values, theoretical_memory, '--', color='gray', 
                        label='Theoretical log₂(N)', linewidth=2)
            
            ax1.set_xlabel('Code Size (N)', fontsize=12)
            ax1.set_ylabel('Memory Levels', fontsize=12)
            ax1.set_title('Memory Usage Validation', fontsize=14, fontweight='bold')
            ax1.legend(fontsize=11)
            ax1.grid(True, alpha=0.3)
            
            # 2. Total operations vs N
            ax2.loglog(N_values, swap_ops, 'o-', color='blue',
                      label='Swap Operations', linewidth=2, markersize=6)
            ax2.loglog(N_values, amp_iterations, 's-', color='red',
                      label='Amplification Iterations', linewidth=2, markersize=6)
            
            ax2.set_xlabel('Code Size (N)', fontsize=12)
            ax2.set_ylabel('Total Operations', fontsize=12)
            ax2.set_title('Operation Scaling', fontsize=14, fontweight='bold')
            ax2.legend(fontsize=11)
            ax2.grid(True, alpha=0.3)
            
            # 3. Gate complexity scaling
            ax3.loglog(N_values, gate_complexity, 'o-', color='green',
                      linewidth=2, markersize=6)
            
            # Add reference lines for different scalings
            ref_linear = [N * 10 for N in N_values]
            ref_log = [np.log2(N) * 100 for N in N_values]
            
            ax3.loglog(N_values, ref_linear, '--', color='red', alpha=0.7, label='O(N)')
            ax3.loglog(N_values, ref_log, '--', color='blue', alpha=0.7, label='O(N log N)')
            
            ax3.set_xlabel('Code Size (N)', fontsize=12)
            ax3.set_ylabel('Total Gate Count', fontsize=12)
            ax3.set_title('Gate Complexity Scaling', fontsize=14, fontweight='bold')
            ax3.legend(fontsize=11)
            ax3.grid(True, alpha=0.3)
            
            # 4. Memory efficiency
            memory_efficiency = [m/t if t > 0 else 1 for m, t in zip(memory_used, theoretical_memory)]
            
            ax4.semilogx(N_values, memory_efficiency, 'o-', color='purple',
                        linewidth=2, markersize=6)
            ax4.axhline(y=1.0, color='gray', linestyle='--', alpha=0.7, label='Theoretical Optimum')
            
            ax4.set_xlabel('Code Size (N)', fontsize=12)
            ax4.set_ylabel('Memory Efficiency', fontsize=12)
            ax4.set_title('Memory Efficiency (Actual/Theoretical)', fontsize=14, fontweight='bold')
            ax4.legend(fontsize=11)
            ax4.grid(True, alpha=0.3)
            ax4.set_ylim(0.8, 1.2)
        
        plt.tight_layout()
        
        filename = f"resource_overhead.{save_format}"
        filepath = os.path.join(self.figures_dir, filename)
        plt.savefig(filepath, dpi=300, bbox_inches='tight', format=save_format)
        plt.close()
        
        return filepath
    
    def plot_amplification_efficiency(self, save_format: str = 'pdf') -> str:
        """Plot amplitude amplification efficiency analysis."""
        fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(14, 10))
        
        amp_data = self.data['amplification']
        
        purity_levels = amp_data['purity_levels']
        initial_probs = amp_data['initial_success_probs']
        optimal_iters = amp_data['optimal_iterations']
        actual_iters = amp_data['actual_iterations_used']
        final_probs = amp_data['final_success_probs']
        gains = amp_data['amplification_gains']
        gate_overheads = amp_data['gate_overheads']
        
        # 1. Success probability amplification
        ax1.plot(purity_levels, initial_probs, 'o-', color='red',
                label='Initial Success Prob', linewidth=2, markersize=5)
        ax1.plot(purity_levels, final_probs, 's-', color='green',
                label='Amplified Success Prob', linewidth=2, markersize=5)
        
        ax1.set_xlabel('Purity Parameter λ', fontsize=12)
        ax1.set_ylabel('Success Probability', fontsize=12)
        ax1.set_title('Amplitude Amplification Effect', fontsize=14, fontweight='bold')
        ax1.legend(fontsize=11)
        ax1.grid(True, alpha=0.3)
        ax1.set_ylim(0, 1.05)
        
        # 2. Required iterations
        ax2.plot(purity_levels, optimal_iters, 'o-', color='blue',
                label='Optimal Iterations', linewidth=2, markersize=5)
        ax2.plot(purity_levels, actual_iters, 's-', color='orange',
                label='Actual Iterations', linewidth=2, markersize=5)
        
        ax2.set_xlabel('Purity Parameter λ', fontsize=12)
        ax2.set_ylabel('Amplification Iterations', fontsize=12)
        ax2.set_title('Iteration Requirements', fontsize=14, fontweight='bold')
        ax2.legend(fontsize=11)
        ax2.grid(True, alpha=0.3)
        
        # 3. Amplification gain
        ax3.semilogy(purity_levels, gains, 'o-', color='purple',
                    linewidth=2, markersize=5)
        
        ax3.set_xlabel('Purity Parameter λ', fontsize=12)
        ax3.set_ylabel('Amplification Gain', fontsize=12)
        ax3.set_title('Success Probability Gain', fontsize=14, fontweight='bold')
        ax3.grid(True, alpha=0.3)
        
        # 4. Gate overhead
        ax4.semilogy(purity_levels, gate_overheads, 'o-', color='brown',
                    linewidth=2, markersize=5)
        
        ax4.set_xlabel('Purity Parameter λ', fontsize=12)
        ax4.set_ylabel('Gate Overhead', fontsize=12)
        ax4.set_title('Implementation Cost', fontsize=14, fontweight='bold')
        ax4.grid(True, alpha=0.3)
        
        # Add efficiency regions
        ax1.axvspan(0.7, 1.0, alpha=0.2, color='green', label='High Efficiency')
        ax1.axvspan(0.0, 0.3, alpha=0.2, color='red', label='High Overhead')
        ax1.legend(fontsize=10)
        
        plt.tight_layout()
        
        filename = f"amplification_efficiency.{save_format}"
        filepath = os.path.join(self.figures_dir, filename)
        plt.savefig(filepath, dpi=300, bbox_inches='tight', format=save_format)
        plt.close()
        
        return filepath
    
    def create_main_figure(self, save_format: str = 'pdf') -> str:
        """Create main combined figure (Figure 1 style for paper)."""
        fig = plt.figure(figsize=(16, 12))
        
        # Create a 3x3 grid with some merged cells
        gs = fig.add_gridspec(3, 3, hspace=0.3, wspace=0.3)
        
        # A. Memory scaling (top left, large)
        ax1 = fig.add_subplot(gs[0, :2])
        if 'memory_scaling' in self.data:
            data = self.data['memory_scaling']
            N_values = data['N_values']
            streaming = data['streaming_memory']
            standard = data['standard_qec_memory']
            
            ax1.loglog(N_values, streaming, 'o-', color=PROTOCOL_COLORS['streaming_qec'],
                      label='Streaming QEC (O(log N))', linewidth=3, markersize=8)
            ax1.loglog(N_values, standard, 's-', color=PROTOCOL_COLORS['surface_code'],
                      label='Standard QEC (O(N))', linewidth=3, markersize=8)
            
            ax1.set_xlabel('Number of Input States (N)')
            ax1.set_ylabel('Memory Requirements')
            ax1.set_title('A. Memory Scaling Advantage', fontweight='bold')
            ax1.legend()
            ax1.grid(True, alpha=0.3)
        
        # B. Error evolution (top right)
        ax2 = fig.add_subplot(gs[0, 2])
        if 'evolution' in self.data:
            # Plot representative error evolution
            evolution_data = self.data['evolution']
            depolarizing_examples = [d for d in evolution_data 
                                   if d['noise_type'] == 'depolarizing' 
                                   and d['physical_error_rate'] == 0.3]
            
            if depolarizing_examples:
                data = depolarizing_examples[0]
                ax2.semilogy(data['iterations'], data['logical_errors'], 'o-',
                           color=PROTOCOL_COLORS['depolarizing'], linewidth=2)
                
                ax2.set_xlabel('Purification Level')
                ax2.set_ylabel('Logical Error')
                ax2.set_title('B. Error Reduction', fontweight='bold')
                ax2.grid(True, alpha=0.3)
        
        # C. Phase diagram (middle left)
        ax3 = fig.add_subplot(gs[1, 0])
        if 'phase_diagrams' in self.data:
            phase_data = self.data['phase_diagrams']
            depolarizing_phase = [d for d in phase_data if d['noise_type'] == 'depolarizing']
            
            if depolarizing_phase:
                data = depolarizing_phase[0]
                error_rates = np.array(data['error_rates'])
                code_sizes = np.array(data['code_sizes'])
                success_matrix = np.array(data['success_matrix'])
                
                X, Y = np.meshgrid(code_sizes, error_rates)
                ax3.contourf(X, Y, success_matrix, levels=[0, 0.5, 1], 
                           colors=['lightcoral', 'lightgreen'], alpha=0.8)
                
                ax3.set_xscale('log', base=2)
                ax3.set_xlabel('Code Size (N)')
                ax3.set_ylabel('Error Rate')
                ax3.set_title('C. Phase Diagram', fontweight='bold')
                ax3.grid(True, alpha=0.3)
        
        # D. QEC comparison (middle center)
        ax4 = fig.add_subplot(gs[1, 1])
        if 'qec_comparisons' in self.data:
            comparison_data = self.data['qec_comparisons']
            protocols = [d['protocol_name'].split()[0] for d in comparison_data]
            thresholds = [d['threshold'] for d in comparison_data]
            
            bars = ax4.bar(range(len(protocols)), thresholds, 
                          color=[PROTOCOL_COLORS.get(p.lower(), '#666666') for p in protocols],
                          alpha=0.8)
            
            ax4.set_ylabel('Error Threshold')
            ax4.set_title('D. Protocol Comparison', fontweight='bold')
            ax4.set_xticks(range(len(protocols)))
            ax4.set_xticklabels(protocols, rotation=45, ha='right')
            ax4.grid(True, alpha=0.3)
        
        # E. Convergence (middle right)
        ax5 = fig.add_subplot(gs[1, 2])
        if 'convergence' in self.data:
            convergence_data = self.data['convergence']
            # Plot a few representative curves
            for i, data in enumerate(convergence_data[::2]):  # Every other curve
                if i < 4:  # Limit to 4 curves
                    levels = data['purification_levels']
                    purity = data['purity_evolution']
                    ax5.plot(levels, purity, 'o-', linewidth=2, markersize=4,
                           label=f'δ={data["initial_delta"]}')
            
            ax5.set_xlabel('Purification Level')
            ax5.set_ylabel('Purity λ')
            ax5.set_title('E. Convergence', fontweight='bold')
            ax5.legend(fontsize=9)
            ax5.grid(True, alpha=0.3)
        
        # F. Noise comparison (bottom left)
        ax6 = fig.add_subplot(gs[2, 0])
        if 'noise_analysis' in self.data:
            noise_analysis = self.data['noise_analysis']
            error_rates = [data['physical_error_rate'] for data in noise_analysis]
            
            # Extract comparison data
            depolarizing_final = [data['final_logical_errors'][0] for data in noise_analysis]
            pauli_final = [data['final_logical_errors'][1] if len(data['final_logical_errors']) > 1 
                          else data['final_logical_errors'][0] for data in noise_analysis]
            
            ax6.semilogy(error_rates, depolarizing_final, 'o-', 
                        color=PROTOCOL_COLORS['depolarizing'], label='Depolarizing')
            ax6.semilogy(error_rates, pauli_final, 's-', 
                        color=PROTOCOL_COLORS['symmetric_pauli'], label='Pauli')
            
            ax6.set_xlabel('Physical Error Rate')
            ax6.set_ylabel('Final Logical Error')
            ax6.set_title('F. Noise Comparison', fontweight='bold')
            ax6.legend(fontsize=9)
            ax6.grid(True, alpha=0.3)
        
        # G. Resource scaling (bottom center)
        ax7 = fig.add_subplot(gs[2, 1])
        if 'resource' in self.data:
            resource_data = self.data['resource']
            depolarizing_resources = [d for d in resource_data if d['noise_type'] == 'depolarizing']
            
            if depolarizing_resources:
                N_values = [d['N'] for d in depolarizing_resources]
                gate_complexity = [d['gate_complexity'] for d in depolarizing_resources]
                
                ax7.loglog(N_values, gate_complexity, 'o-', color='green', linewidth=2)
                
                ax7.set_xlabel('Code Size (N)')
                ax7.set_ylabel('Gate Count')
                ax7.set_title('G. Resource Scaling', fontweight='bold')
                ax7.grid(True, alpha=0.3)
        
        # H. Key advantage summary (bottom right)
        ax8 = fig.add_subplot(gs[2, 2])
        ax8.axis('off')  # Turn off axes for text summary
        
        # Create advantage summary text
        advantages = [
            "Key Advantages:",
            "• O(log N) memory scaling",
            "• High error thresholds", 
            "• Streaming implementation",
            "• Deterministic operation",
            "",
            "Applications:",
            "• Large-scale quantum computing",
            "• Resource-constrained systems",
            "• Continuous error correction"
        ]
        
        ax8.text(0.05, 0.95, '\n'.join(advantages), transform=ax8.transAxes, 
                fontsize=11, verticalalignment='top',
                bbox=dict(boxstyle="round,pad=0.5", facecolor="lightblue", alpha=0.8))
        
        ax8.set_title('H. Key Results', fontweight='bold')
        
        # Add overall title
        fig.suptitle('Streaming Quantum State Purification: A Nonlinear QEC Protocol', 
                    fontsize=18, fontweight='bold', y=0.98)
        
        filename = f"main_figure_combined.{save_format}"
        filepath = os.path.join(self.figures_dir, filename)
        plt.savefig(filepath, dpi=300, bbox_inches='tight', format=save_format)
        plt.close()
        
        return filepath


def main():
    """Main function to generate all figures."""
    import sys
    
    # Parse command line arguments
    data_dir = "data"
    figures_dir = "figures"
    save_format = "pdf"
    
    if '--data-dir' in sys.argv:
        idx = sys.argv.index('--data-dir')
        if idx + 1 < len(sys.argv):
            data_dir = sys.argv[idx + 1]
    
    if '--figures-dir' in sys.argv:
        idx = sys.argv.index('--figures-dir')
        if idx + 1 < len(sys.argv):
            figures_dir = sys.argv[idx + 1]
    
    if '--format' in sys.argv:
        idx = sys.argv.index('--format')
        if idx + 1 < len(sys.argv):
            save_format = sys.argv[idx + 1]
    
    try:
        # Create figure generator
        generator = StreamingQECFigureGenerator(data_dir, figures_dir)
        
        # Generate all figures
        saved_figures = generator.generate_all_figures(save_format)
        
        print("\n" + "="*60)
        print("FIGURE GENERATION COMPLETE")
        print("="*60)
        print(f"Generated {len(saved_figures)} figures")
        print(f"Saved to: {figures_dir}")
        print(f"Format: {save_format.upper()}")
        
        print("\nGenerated figures:")
        for name, path in saved_figures.items():
            print(f"  {name}: {os.path.basename(path)}")
        
        return saved_figures
        
    except FileNotFoundError as e:
        print(f"Error: {e}")
        print("Make sure to run comprehensive_data_generation.py first!")
        return None
    except Exception as e:
        print(f"Error generating figures: {e}")
        return None


if __name__ == "__main__":
    main()