"""
Updated figure generation script for streaming QEC protocol paper.
Loads data generated by comprehensive_data_generator.py and creates individual publication-quality figures.

Each plot is saved as a separate file - no combined figures.
"""

import os
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from typing import Dict, List, Tuple, Any, Optional
import warnings
from glob import glob

# Set publication-quality plotting parameters
plt.style.use('seaborn-v0_8-paper')
sns.set_palette("husl")

plt.rcParams.update({
    'font.size': 20,
    'axes.titlesize': 30,
    'axes.labelsize': 25,
    'xtick.labelsize': 20,
    'ytick.labelsize': 20,
    'legend.fontsize': 20,
    'figure.titlesize': 30,
    'font.family': 'DejaVu Sans',
    'mathtext.fontset': 'dejavusans',
    'axes.linewidth': 1.2,
    'grid.linewidth': 0.8,
    'lines.linewidth': 3,
    'lines.markersize': 8
})

# Color schemes
PROTOCOL_COLORS = {
    'depolarizing': '#2E86AB',
    'symmetric_pauli': '#A23B72', 
    'dephasing': '#F18F01',
    'streaming_qec': '#2E86AB',
    'surface_code': '#A23B72',
    'spinor_code': '#F18F01'
}


class StreamingQECPlotter:
    """Generate individual publication-quality figures for streaming QEC paper."""
    
    def __init__(self, data_dir: str = "data", figures_dir: str = "figures"):
        self.data_dir = data_dir
        self.figures_dir = figures_dir
        os.makedirs(figures_dir, exist_ok=True)
        
        # Load all available data
        self.evolution_data = self._load_data_type('evolution')
        self.threshold_data = self._load_data_type('threshold') 
        self.resource_data = self._load_data_type('resource')
        
        print(f"Loaded data:")
        print(f"  Evolution records: {len(self.evolution_data) if self.evolution_data else 0}")
        print(f"  Threshold records: {len(self.threshold_data) if self.threshold_data else 0}")
        print(f"  Resource records: {len(self.resource_data) if self.resource_data else 0}")
    
    def _load_data_type(self, data_type: str) -> List[Dict]:
        """Load most recent data of specified type."""
        try:
            # Look for JSON files with the data type
            pattern = os.path.join(self.data_dir, data_type, f"{data_type}_*.json")
            files = glob(pattern)
            
            if not files:
                print(f"Warning: No {data_type} data files found at {pattern}")
                return []
            
            # Use most recent file
            latest_file = sorted(files)[-1]
            print(f"Loading {data_type} data from: {os.path.basename(latest_file)}")
            
            with open(latest_file, 'r') as f:
                data = json.load(f)
            
            return data if isinstance(data, list) else []
            
        except Exception as e:
            print(f"Error loading {data_type} data: {e}")
            return []
    
    def plot_grafe_figure4_analog(self, save_format: str = 'pdf') -> Optional[str]:
        """
        Create analog of Grafe's Figure 4: Logical error vs physical error rate 
        for different code sizes, showing threshold behavior.
        """
        if not self.threshold_data:
            print("Warning: No threshold data available for Grafe Figure 4 analog")
            return None
        
        fig, ax = plt.subplots(figsize=(10, 8))
        
        # Auto-discover available noise types and focus on depolarizing
        available_noise_types = list(set(d['noise_type'] for d in self.threshold_data))
        print(f"Available noise types: {available_noise_types}")
        
        # Focus on depolarizing noise for main result
        depolarizing_data = [d for d in self.threshold_data if d['noise_type'] == 'depolarizing']
        
        if not depolarizing_data:
            print("Warning: No depolarizing data for Figure 4 analog")
            return None
        
        # Auto-discover all available code sizes and sort them
        code_sizes = sorted(list(set(d['N'] for d in depolarizing_data)))
        print(f"Found code sizes: {code_sizes}")
        
        # Generate colors dynamically based on number of code sizes
        colors = plt.cm.viridis(np.linspace(0, 1, len(code_sizes)))
        
        plotted_curves = 0
        
        # Plot threshold curves for each code size
        for i, N in enumerate(code_sizes):
            # Find data for this code size
            size_data = [d for d in depolarizing_data if d['N'] == N]
            
            if size_data:
                data = size_data[0]  # Should only be one per code size
                
                physical_rates = np.array(data['physical_error_rates'])
                final_errors = np.array(data['final_logical_errors'])
                
                print(f"Code size N={N}: {len(physical_rates)} error rate points")
                
                # Filter out invalid data
                valid_mask = np.isfinite(final_errors) & (final_errors > 0)
                
                if np.sum(valid_mask) > 0:
                    valid_physical = physical_rates[valid_mask]
                    valid_final = final_errors[valid_mask]
                    
                    ax.loglog(valid_physical, valid_final, 'o-', 
                             color=colors[i], linewidth=3, markersize=8,
                             label=f'N = {N}', alpha=0.8)
                    plotted_curves += 1
        
        if plotted_curves == 0:
            print("Warning: No valid curves to plot")
            ax.text(0.5, 0.5, 'No Valid Threshold Data', 
                   transform=ax.transAxes, ha='center', va='center', fontsize=16)
            return None
        
        # Add "no improvement" reference line
        physical_range = np.logspace(-2, 0, 100)
        ax.loglog(physical_range, physical_range, '--', 
                 color='gray', linewidth=2, alpha=0.7, label='No Correction')
        
        ax.set_xscale('linear')
        # Formatting to match Grafe style
        ax.set_xlabel(r'Physical Error Rate, $\delta$', fontsize=25)
        ax.set_ylabel(r'Final Logical Error Rate, $\varepsilon_L$', fontsize=25)
        ax.set_title('Streaming QEC Threshold \n(Depolarizing Noise, d=2)', 
                    fontsize=30)
        
        ax.legend(fontsize=14, loc='upper left')
        # ax.grid(True, alpha=0.3)
        
        # Set reasonable axis limits
        ax.set_xlim(0.09, 1.0)
        ax.set_ylim(1e-5, 1.0)
        
        # Add threshold annotation
        # ax.text(0.7, 0.8, 'Below diagonal:\nError correction', 
        #         transform=ax.transAxes, fontsize=12,
        #         bbox=dict(boxstyle="round,pad=0.5", facecolor="lightgreen", alpha=0.8))
        
        # ax.text(0.3, 0.2, 'Above diagonal:\nNo improvement', 
        #         transform=ax.transAxes, fontsize=12,
        #         bbox=dict(boxstyle="round,pad=0.5", facecolor="lightcoral", alpha=0.8))
        
        plt.tight_layout()
        
        filename = f"grafe_figure4_analog.{save_format}"
        filepath = os.path.join(self.figures_dir, filename)
        plt.savefig(filepath, dpi=300, bbox_inches='tight', format=save_format)
        plt.close()
        
        print(f"Saved Grafe Figure 4 analog: {filename} with {plotted_curves} curves")
        return filepath
    
    # def plot_error_evolution(self, save_format: str = 'pdf') -> Optional[str]:
    #     """Plot logical error evolution through purification levels."""
    #     if not self.evolution_data:
    #         print("Warning: No evolution data available")
    #         return None
        
    #     fig, ax = plt.subplots(figsize=(10, 8))
        
    #     # Auto-discover all noise types in the data
    #     available_noise_types = sorted(list(set(d['noise_type'] for d in self.evolution_data)))
    #     print(f"Found noise types: {available_noise_types}")
        
    #     plotted_any = False
    #     linestyles = ['solid', 'dotted', 'dashed', 'dashdot', 'densely dashdotdotted']  # Cycle through linestyles
        
    #     for noise_idx, noise_type in enumerate(available_noise_types):
    #         # Get all data for this noise type
    #         noise_data = [d for d in self.evolution_data if d['noise_type'] == noise_type]
            
    #         # Find best code size (largest available)
    #         available_sizes = list(set(d['N'] for d in noise_data))
    #         target_N = max(available_sizes)
            
    #         # Get all error rates for this noise type and code size
    #         target_data = [d for d in noise_data if d['N'] == target_N]
    #         error_rates = sorted(list(set(d['physical_error_rate'] for d in target_data)))
            
    #         print(f"{noise_type}: {len(error_rates)} error rates for N={target_N}")
    #         if noise_type == 'depolarizing':
    #             legend_label = '$\delta$'
    #         else:
    #             legend_label = 'p'
            
    #         # Generate colors for this noise type
    #         base_color = PROTOCOL_COLORS.get(noise_type, '#666666')
            
    #         for rate_idx, error_rate in enumerate(error_rates):
    #             matches = [d for d in target_data if d['physical_error_rate'] == error_rate]
                
    #             if matches:
    #                 data = matches[0]
    #                 iterations = data['iterations'] 
    #                 logical_errors = data['logical_errors']
                    
    #                 if len(iterations) > 0 and len(logical_errors) > 0:
    #                     # Vary alpha for different error rates within same noise type
    #                     alpha = 1.0 - 0.6 * (rate_idx / max(1, len(error_rates) - 1))
    #                     linestyle = linestyles[noise_idx % len(linestyles)]
                        
    #                     ax.semilogy(iterations, logical_errors, 'o-', 
    #                                color=base_color, linestyle=linestyle, alpha=max(0.4, alpha),
    #                                linewidth=3, markersize=6,
    #                                label=rf'{noise_type.replace("_", " ").title()}, {legend_label}={error_rate:.3f}')
    #                     plotted_any = True
        
    #     if not plotted_any:
    #         print("Warning: No valid evolution data to plot")
    #         ax.text(0.5, 0.5, 'No Evolution Data Available', 
    #                transform=ax.transAxes, ha='center', va='center', fontsize=16)

    #     ax.set_xlabel(r'Purification Level, $n$', fontsize=25)
    #     ax.set_ylabel(r'Logical Error Rate, $\varepsilon_L^{(n)}$', fontsize=25)
    #     ax.set_title('Error Evolution Through Purification', fontsize=30)
    #     ax.legend(fontsize=14, ncol=2)
    #     ax.grid(True, alpha=0.3)
        
    #     plt.tight_layout()
        
    #     filename = f"error_evolution.{save_format}"
    #     filepath = os.path.join(self.figures_dir, filename)
    #     plt.savefig(filepath, dpi=300, bbox_inches='tight', format=save_format)
    #     plt.close()
        
    #     print(f"Saved error evolution plot: {filename}")
    #     return filepath
    
    
    def plot_error_evolution(self, save_format: str = 'pdf') -> Optional[str]:
        """Plot logical error evolution through purification levels."""
        if not self.evolution_data:
            print("Warning: No evolution data available")
            return None
    
        # Create figure with 2 subplots side by side
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(20, 8))
    
        # Auto-discover all noise types in the data
        available_noise_types = sorted(list(set(d['noise_type'] for d in self.evolution_data)))
        print(f"Found noise types: {available_noise_types}")
    
        # Separate noise types
        depolarizing_types = [nt for nt in available_noise_types if 'depolarizing' in nt.lower()]
        pauli_types = [nt for nt in available_noise_types if 'depolarizing' not in nt.lower()]
    
        print(f"Depolarizing types: {depolarizing_types}")
        print(f"Pauli types: {pauli_types}")
    
        linestyles = ['solid', 'dotted', 'dashed', 'dashdot', 'densely dashdotdotted']
        plotted_any = [False, False]  # Track if we plotted anything for each subplot
    
        # Function to plot data for a given set of noise types on a specific axis
        def plot_noise_group(ax, noise_types, subplot_idx, title_suffix):
            for noise_idx, noise_type in enumerate(noise_types):
                # Get all data for this noise type
                noise_data = [d for d in self.evolution_data if d['noise_type'] == noise_type]
            
                # Find best code size (largest available)
                available_sizes = list(set(d['N'] for d in noise_data))
                target_N = max(available_sizes)
            
                # Get all error rates for this noise type and code size
                target_data = [d for d in noise_data if d['N'] == target_N]
                error_rates = sorted(list(set(d['physical_error_rate'] for d in target_data)))
            
                print(f"{noise_type}: {len(error_rates)} error rates for N={target_N}")
            
                # Set legend label based on noise type
                if noise_type == 'depolarizing':
                    legend_label = '$\delta$'
                else:
                    legend_label = 'p'
            
                # Generate colors for this noise type
                base_color = PROTOCOL_COLORS.get(noise_type, '#666666')
            
                for rate_idx, error_rate in enumerate(error_rates):
                    matches = [d for d in target_data if d['physical_error_rate'] == error_rate]
                
                    if matches:
                        data = matches[0]
                        iterations = data['iterations'] 
                        logical_errors = data['logical_errors']
                    
                        if len(iterations) > 0 and len(logical_errors) > 0:
                            # Vary alpha for different error rates within same noise type
                            alpha = 1.0 - 0.6 * (rate_idx / max(1, len(error_rates) - 1))
                            linestyle = linestyles[noise_idx % len(linestyles)]
                        
                            ax.semilogy(iterations, logical_errors, 'o-', 
                                    color=base_color, linestyle=linestyle, alpha=max(0.4, alpha),
                                    linewidth=3, markersize=6,
                                    label=rf'{noise_type.replace("_", " ").title()}, {legend_label}={error_rate:.3f}')
                            plotted_any[subplot_idx] = True
        
            # Set labels and formatting for this subplot
            ax.set_xlabel(r'Purification Level, $n$', fontsize=20)
            ax.set_ylabel(r'Logical Error Rate, $\varepsilon_L^{(n)}$', fontsize=20)
            ax.set_title(f'Error Evolution - {title_suffix}', fontsize=24)
            # ax.grid(True, alpha=0.3)
        
            if not plotted_any[subplot_idx]:
                ax.text(0.5, 0.5, f'No {title_suffix} Data Available', 
                    transform=ax.transAxes, ha='center', va='center', fontsize=16)
            else:
                ax.legend(fontsize=12, loc='best')
    
        # Plot depolarizing noise types on left subplot
        plot_noise_group(ax1, depolarizing_types, 0, "Depolarizing Noise")
    
        # Plot Pauli noise types on right subplot  
        plot_noise_group(ax2, pauli_types, 1, "Pauli Errors")
        
        ax1.text(0.90, 0.95, '(a)', transform=ax1.transAxes, fontsize=18, fontweight='bold')
        ax2.text(0.90, 0.95, '(b)', transform=ax2.transAxes, fontsize=18, fontweight='bold')
    
        plt.tight_layout()
    
        filename = f"error_evolution.{save_format}"
        filepath = os.path.join(self.figures_dir, filename)
        plt.savefig(filepath, dpi=300, bbox_inches='tight', format=save_format)
        plt.close()
    
        print(f"Saved error evolution plot: {filename}")
        return filepath
    
    def plot_fidelity_evolution(self, save_format: str = 'pdf') -> Optional[str]:
        """Plot fidelity evolution through purification levels."""
        if not self.evolution_data:
            print("Warning: No evolution data available")
            return None
        
        fig, ax = plt.subplots(figsize=(10, 8))
        
        # Auto-discover all available error rates for depolarizing noise
        depolarizing_data = [d for d in self.evolution_data if d['noise_type'] == 'depolarizing']
        
        if not depolarizing_data:
            print("Warning: No depolarizing evolution data available")
            return None
        
        # Find best code size to use (largest available)
        available_sizes = list(set(d['N'] for d in depolarizing_data))
        target_N = max(available_sizes)
        
        # Get all unique error rates for this code size
        target_data = [d for d in depolarizing_data if d['N'] == target_N]
        error_rates = sorted(list(set(d['physical_error_rate'] for d in target_data)))
        
        print(f"Found {len(error_rates)} error rates for N={target_N}: {error_rates}")
        
        # Generate colors dynamically
        colors = plt.cm.viridis(np.linspace(0, 1, len(error_rates)))
        
        plotted_any = False
        
        for i, error_rate in enumerate(error_rates):
            matches = [d for d in target_data if d['physical_error_rate'] == error_rate]
            
            if matches:
                data = matches[0]
                iterations = data['iterations']
                fidelities = data['fidelities']
                
                if len(iterations) > 0 and len(fidelities) > 0:
                    ax.plot(iterations, fidelities, 'o-', color=colors[i],
                           label=rf'$\delta$ = {error_rate:.3f}', linewidth=3, markersize=8)
                    plotted_any = True
        
        if not plotted_any:
            print("Warning: No valid fidelity data to plot")
            ax.text(0.5, 0.5, 'No Fidelity Data Available', 
                   transform=ax.transAxes, ha='center', va='center', fontsize=16)
        
        # Add target fidelity line
        ax.axhline(y=0.99, color='black', linestyle=':', alpha=0.7, 
                  linewidth=2, label='Target Fidelity 0.99')
        
        ax.set_xlabel(r'Purification Level, $n$', fontsize=25)
        ax.set_ylabel('State Fidelity', fontsize=25)
        ax.set_title(f'Fidelity Evolution (Depolarizing Noise, N={target_N})', fontsize=30)
        ax.legend(fontsize=14)
        # ax.grid(True, alpha=0.3)
        ax.set_ylim(0, 1.05)
        
        plt.tight_layout()
        
        filename = f"fidelity_evolution.{save_format}"
        filepath = os.path.join(self.figures_dir, filename)
        plt.savefig(filepath, dpi=300, bbox_inches='tight', format=save_format)
        plt.close()
        
        print(f"Saved fidelity evolution plot: {filename}")
        return filepath
    
    def plot_memory_scaling(self, save_format: str = 'pdf') -> Optional[str]:
        """Plot memory scaling - KEY ADVANTAGE FIGURE."""
        if not self.resource_data:
            print("Warning: No resource data available for memory scaling")
            return None
        
        fig, ax = plt.subplots(figsize=(10, 8))
        
        # Extract memory data for depolarizing noise
        depolarizing_resources = [d for d in self.resource_data if d['noise_type'] == 'depolarizing']
        
        if not depolarizing_resources:
            print("Warning: No depolarizing resource data")
            return None
        
        # Group by code size
        N_values = sorted(list(set(d['N'] for d in depolarizing_resources)))
        memory_used = []
        theoretical_memory = []
        
        for N in N_values:
            matches = [d for d in depolarizing_resources if d['N'] == N]
            if matches:
                data = matches[0]
                memory_used.append(data['memory_levels_used'])
                theoretical_memory.append(data['theoretical_memory'])
        
        if len(N_values) > 0:
            # Streaming QEC (actual)
            ax.loglog(N_values, memory_used, 'o-', color=PROTOCOL_COLORS['streaming_qec'],
                     label='Streaming QEC (Actual)', linewidth=4, markersize=10)
            
            # Theoretical O(log N)
            ax.loglog(N_values, theoretical_memory, '--', color='gray', 
                     label='Theoretical O(log N)', linewidth=3)
            
            # Standard QEC O(N) for comparison
            standard_memory = [N * 0.1 for N in N_values]  # Scaled for visibility
            ax.loglog(N_values, standard_memory, 's-', color=PROTOCOL_COLORS['surface_code'],
                     label='Standard QEC O(N)', linewidth=4, markersize=10)
            
            # Add scaling annotations
            ax.text(0.75, 0.85, 'O(N)', transform=ax.transAxes, fontsize=18, 
                    color=PROTOCOL_COLORS['surface_code'])
            ax.text(0.75, 0.15, 'O(log N)', transform=ax.transAxes, fontsize=18,
                    color=PROTOCOL_COLORS['streaming_qec'])

            # Calculate and show advantage
            if len(N_values) > 1:
                max_advantage = max(standard_memory) / max(memory_used)
                ax.text(0.05, 0.85, f'Memory Advantage:\n{max_advantage:.1f}× reduction\nfor N={max(N_values)}', 
                        transform=ax.transAxes, fontsize=14, 
                        bbox=dict(boxstyle="round,pad=0.5", facecolor="yellow", alpha=0.8))

        ax.set_xlabel('Number of Input States (N)', fontsize=16)
        ax.set_ylabel('Memory Requirements (levels)', fontsize=16)
        ax.set_title('Memory Scaling: Streaming vs Standard QEC', fontsize=18)
        ax.legend(fontsize=14, loc='upper left')
        # ax.grid(True, alpha=0.3)
        
        plt.tight_layout()
        
        filename = f"memory_scaling.{save_format}"
        filepath = os.path.join(self.figures_dir, filename)
        plt.savefig(filepath, dpi=300, bbox_inches='tight', format=save_format)
        plt.close()
        
        print(f"Saved memory scaling plot: {filename}")
        return filepath
    
    def plot_noise_comparison(self, save_format: str = 'pdf') -> Optional[str]:
        """Compare performance across different noise models."""
        if not self.threshold_data:
            print("Warning: No threshold data for noise comparison")
            return None
        
        fig, ax = plt.subplots(figsize=(10, 8))
        
        # Get unique noise types
        noise_types = list(set(d['noise_type'] for d in self.threshold_data))
        
        
        plotted_any = False
        
        for noise_type in noise_types:
            # Find best code size to use (largest available)
            available_sizes = list(set(d['N'] for d in self.threshold_data))
            target_N = max(available_sizes)
            # Find representative data (fixed code size)
            matches = [d for d in self.threshold_data
                      if d['noise_type'] == noise_type and d['N'] == target_N]

            if matches:
                data = matches[0]
                physical_rates = np.array(data['physical_error_rates'])
                final_errors = np.array(data['final_logical_errors'])
                
                # Filter valid data
                valid_mask = np.isfinite(final_errors) & (final_errors > 0)
                
                if np.sum(valid_mask) > 0:
                    valid_physical = physical_rates[valid_mask]
                    valid_final = final_errors[valid_mask]
                    
                    color = PROTOCOL_COLORS.get(noise_type, '#666666')
                    ax.loglog(valid_physical, valid_final, 'o-', 
                             color=color, linewidth=3, markersize=8,
                             label=f'{noise_type.replace("_", " ").title()}')
                    plotted_any = True
        
        if plotted_any:
            # Add reference line
            physical_range = np.logspace(-2, 0, 100)
            ax.loglog(physical_range, physical_range, '--', 
                     color='gray', linewidth=2, alpha=0.7, label='No Correction')
        
        ax.set_xscale('linear')
        # ax.set_yscale('linear')
        ax.set_xlabel('Physical Error Rate', fontsize=25)
        ax.set_ylabel('Final Logical Error Rate', fontsize=25)
        ax.set_title(f'Noise Model Comparison (N={target_N})', fontsize=30)
        ax.legend(fontsize=14)
        # ax.grid(True, alpha=0.3)
        
        plt.tight_layout()
        
        filename = f"noise_comparison.{save_format}"
        filepath = os.path.join(self.figures_dir, filename)
        plt.savefig(filepath, dpi=300, bbox_inches='tight', format=save_format)
        plt.close()
        
        print(f"Saved noise comparison plot: {filename}")
        return filepath
    
    def plot_resource_overhead(self, save_format: str = 'pdf') -> Optional[str]:
        """Plot resource overhead vs code size."""
        if not self.resource_data:
            print("Warning: No resource data available")
            return None
        
        fig, ax = plt.subplots(figsize=(10, 8))
        
        # Extract data for depolarizing noise
        depolarizing_resources = [d for d in self.resource_data if d['noise_type'] == 'depolarizing']
        
        if depolarizing_resources:
            N_values = sorted(list(set(d['N'] for d in depolarizing_resources)))
            total_operations = []
            amp_iterations = []
            
            for N in N_values:
                matches = [d for d in depolarizing_resources if d['N'] == N]
                if matches:
                    data = matches[0]
                    total_operations.append(data['total_swap_operations'])
                    amp_iterations.append(data['total_amplification_iterations'])
            
            if len(N_values) > 0:
                ax.loglog(N_values, total_operations, 'o-', color='blue',
                         label='Swap Operations', linewidth=3, markersize=8)
                ax.loglog(N_values, amp_iterations, 's-', color='red',
                         label='Amplification Iterations', linewidth=3, markersize=8)
                
                # Add scaling reference
                ref_linear = [N * 0.5 for N in N_values]
                ax.loglog(N_values, ref_linear, '--', color='gray', alpha=0.7, 
                         label='Linear Scaling')

        ax.set_xlabel('Code Size (N)', fontsize=16)
        ax.set_ylabel('Total Operations', fontsize=16)
        ax.set_title('Resource Overhead Scaling', fontsize=18)
        ax.legend(fontsize=14)
        # ax.grid(True, alpha=0.3)
        
        plt.tight_layout()
        
        filename = f"resource_overhead.{save_format}"
        filepath = os.path.join(self.figures_dir, filename)
        plt.savefig(filepath, dpi=300, bbox_inches='tight', format=save_format)
        plt.close()
        
        print(f"Saved resource overhead plot: {filename}")
        return filepath
    
    def plot_error_reduction_ratios(self, save_format: str = 'pdf') -> Optional[str]:
        """Plot error reduction ratios showing improvement factors."""
        if not self.threshold_data:
            print("Warning: No threshold data for error reduction ratios")
            return None
        
        fig, ax = plt.subplots(figsize=(10, 8))
        
        # Focus on depolarizing noise
        depolarizing_data = [d for d in self.threshold_data if d['noise_type'] == 'depolarizing']
        
        # Get different code sizes
        code_sizes = sorted(list(set(d['N'] for d in depolarizing_data)))
        colors = plt.cm.viridis(np.linspace(0, 1, len(code_sizes)))
        
        plotted_any = False
        
        for i, N in enumerate(code_sizes):
            matches = [d for d in depolarizing_data if d['N'] == N]
            
            if matches:
                data = matches[0]
                physical_rates = np.array(data['physical_error_rates'])
                reduction_ratios = np.array(data['error_reduction_ratios'])
                
                # Filter valid data
                valid_mask = np.isfinite(reduction_ratios) & (reduction_ratios > 0)
                
                if np.sum(valid_mask) > 0:
                    valid_physical = physical_rates[valid_mask]
                    valid_ratios = reduction_ratios[valid_mask]
                    
                    ax.semilogy(valid_physical, valid_ratios, 'o-', 
                               color=colors[i], linewidth=3, markersize=8,
                               label=f'N = {N}')
                    plotted_any = True
        
        if plotted_any:
            # Add reference line for no improvement
            ax.axhline(y=1.0, color='gray', linestyle='--', alpha=0.7, 
                      linewidth=2, label='No Improvement')

        ax.set_xlabel(r'Physical Error Rate, $\delta$', fontsize=25)
        ax.set_ylabel('Error Reduction Ratio', fontsize=25)
        ax.set_title('Error Reduction Effectiveness', fontsize=30)
        ax.legend(fontsize=14)
        # ax.grid(True, alpha=0.3)
        
        plt.tight_layout()
        
        filename = f"error_reduction_ratios.{save_format}"
        filepath = os.path.join(self.figures_dir, filename)
        plt.savefig(filepath, dpi=300, bbox_inches='tight', format=save_format)
        plt.close()
        
        print(f"Saved error reduction ratios plot: {filename}")
        return filepath
    
    def generate_all_plots(self, save_format: str = 'pdf') -> Dict[str, Optional[str]]:
        """Generate all individual plots."""
        print("\n" + "="*60)
        print("GENERATING ALL INDIVIDUAL PLOTS")
        print("="*60)
        
        plots = {}
        
        # print("\n1. Grafe Figure 4 Analog (KEY PLOT)...")
        # plots['grafe_figure4'] = self.plot_grafe_figure4_analog(save_format)
        
        # print("\n2. Error Evolution...")
        # plots['error_evolution'] = self.plot_error_evolution(save_format)
        
        print("\n3. Fidelity Evolution...")  
        plots['fidelity_evolution'] = self.plot_fidelity_evolution(save_format)
        
        # print("\n4. Memory Scaling...")
        # plots['memory_scaling'] = self.plot_memory_scaling(save_format)
        
        # print("\n5. Noise Model Comparison...")
        # plots['noise_comparison'] = self.plot_noise_comparison(save_format)
        
        # print("\n6. Resource Overhead...")
        # plots['resource_overhead'] = self.plot_resource_overhead(save_format)
        
        # print("\n7. Error Reduction Ratios...")
        # plots['error_reduction'] = self.plot_error_reduction_ratios(save_format)
        
        # Summary
        successful_plots = [name for name, path in plots.items() if path is not None]
        print(f"\n{len(successful_plots)} plots generated successfully:")
        for name in successful_plots:
            print(f"  ✓ {name}")
        
        failed_plots = [name for name, path in plots.items() if path is None]
        if failed_plots:
            print(f"\n{len(failed_plots)} plots failed:")
            for name in failed_plots:
                print(f"  ✗ {name}")
        
        return plots


def main():
    """Main function to generate all plots."""
    import sys
    
    # Parse command line arguments
    data_dir = "data"
    figures_dir = "figures"
    save_format = "pdf"
    
    if '--data-dir' in sys.argv:
        idx = sys.argv.index('--data-dir')
        if idx + 1 < len(sys.argv):
            data_dir = sys.argv[idx + 1]
    
    if '--figures-dir' in sys.argv:
        idx = sys.argv.index('--figures-dir')
        if idx + 1 < len(sys.argv):
            figures_dir = sys.argv[idx + 1]
    
    if '--format' in sys.argv:
        idx = sys.argv.index('--format')
        if idx + 1 < len(sys.argv):
            save_format = sys.argv[idx + 1]
    
    try:
        # Create plotter
        plotter = StreamingQECPlotter(data_dir, figures_dir)
        
        # Generate all plots
        plots = plotter.generate_all_plots(save_format)
        
        print("\n" + "="*60)
        print("PLOT GENERATION COMPLETE")
        print("="*60)
        print(f"Figures saved to: {figures_dir}")
        print(f"Format: {save_format.upper()}")
        
        return plots
        
    except Exception as e:
        print(f"Error generating plots: {e}")
        import traceback
        traceback.print_exc()
        return None


if __name__ == "__main__":
    main()